# stage 1. 소스코드 빌드
FROM node:22.14.0 AS my-build

WORKDIR /app

COPY . ./

RUN npm install 

# 타입스크립트 빌드
RUN npm run build

# ----------------------------------------

# stage 2. 런타임
FROM node:22.14.0

WORKDIR /app

# 빌드된 소스코드 복사
COPY --from=my-build /app/dist ./dist
COPY --from=my-build /app/public ./public
COPY --from=my-build /app/package.json ./package.json

# production 환경 런타임시 필요한 패키지만 설치
RUN npm install --production

# 실행
CMD ["node", "dist/server.js"]