apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-02
spec:
  nodeSelector:
    kubernetes.io/hostname: minikube
  containers:
  - name: nginx-test01
    image: nginx:latest
    volumeMounts:
    - name: hostpath-test01
      mountPath: /mount01
  volumes:
  - name: hostpath-test01
    hostPath:
      path: '/volhost01' # 호스트 경로. (minikube의 경로)
      type: DirectoryOrCreate