# FROM: 베이스 이미지
FROM node:22.14.0

# WORKDIR: 작업 디렉토리 설정
WORKDIR /app

# COPY: 현재 디렉토리의 파일을 컨테이너로 복사
COPY package.json ./
COPY index.js ./

# RUN: 명령어 실행
RUN npm install

# EXPOSE: 컨테이너가 사용할 포트 설정
EXPOSE 3000

# CMD: 컨테이너 시작 시 실행할 명령어
CMD ["node", "index.js"]